### ISSUE TITLE
Revert changes from user

### ISSUE THREAD

**Issue by comradekingu** [WeblateOrg/hosted#285] opened 2021-11-20 04:54 UTC
### Describe the problem

https://hosted.weblate.org/changes/?page=1&limit=20&lang=nb_NO&user=deleted-14768
I don't know if the other contributions are this bad, but this is less than helpful considering the quality one would hope to aim for.
This is too much to revert manually.
Examples:
Yards is dockyards
Grant is stipend
Pause is Go asunder (at best)

### Describe the solution you'd like

Clear all those, possibly everything the user has contributed.
Guessing this person is German, so those might be better.

### Describe alternatives you've considered

Editable Zen view for history
Per-user "Needs editing"-schemes.

**Comment by nijel** [comment] 2021-11-20 06:06
Duplicate of #6371

**Closed by nijel** 2021-11-20 06:06 UTC
Labels: duplicate
